config/routes.rb
Rails.application.routes.draw do
  root :to => "bookers#index"
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  resources :users
  resources :bookers, only: [:index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, optional: true

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: 2..20
  def email_required?
   false
 end
 def email_changed?
   false
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception




  before_action :set_current_user

def set_current_user
  @current_user = User.find_by(id: session[:user_id])
end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: [:name, :email]
    devise_parameter_sanitizer.permit :account_update, keys: [:name]
    devise_parameter_sanitizer.permit :sign_in, keys: [:name]
  end


def after_sign_in_path_for(resource)
    books_path # ログイン後に遷移するpathを設定
  end
end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController
def index

end

def new

end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@books = Book.all
  	@book = Book.new
    @user = current_user
  end

  def create
    @user = current_user
  	@book = Book.new(book_params)

    user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
       redirect_to books_path
    else
         @books = Book.all
         render 'index'
    end
  end

  def show
    @book = Book.find_by(id: params[:id])
    # 変数@userを定義してください
     @user = current_user
     user_id = current_user.id

  end

  def edit
  	@book = Book.find_by(id: params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to books_path
  end

  def destroy
  	 book = Book.find(params[:id])
         book.destroy
        redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	@users = User.all
	@book = Book.find_by(params[:id])
	@user = User.find_by(params[:id])
end

def show
    @user = User.find(params[:id])
    @book = Book.find_by(params[:id])
    @books = Book.all
end
def edit
	@user = User.find(params[:id])
end
def update
	@user = User.find(params[:id])
	@user.update(user_params)
	redirect_to user_path(@user.id)
end

private
  def user_params
	params.require(:user).permit(:name, :profile_image, :introduction)
  end
   def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookers/index.html.erb
<h2>welcome to Bookers !!</h2>
<p>In Bookers,<br>

you can share and exchange your opinions , inpressions , and emotions<br>

about varioius books!</p>

<%= link_to 'Log in', new_user_session_path, class: "btn btn-block btn-info" %>
<%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-block btn-success" %>

app/views/bookers/new.html.erb
<h1>Welcome to Bookers!</h1>

app/views/books/_list.html.erb
<h2>User Info</h2>
       <%= user.name %>
       <%= user.introduction %>
        <p><%= link_to (edit_user_path(user)) , class: "btn btn-block" do %></p>
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        <% end %>

      <h2>New Book</h2>
       <!-- form_for部分 -->
       <%= form_for(book) do |f| %>
         <% if book.errors.any? %>
         <div id="error_explanation">
      <h2><%= book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
       <% end %>

      <h4>Title</h4>
        <%= f.text_field :title %>

      <h4>Opinion</h4>
        <%= f.text_area :body %>

       <br>

       <%= f.submit 'Create Book', :class=>"btn btn-primary btn-block"%>
      <% end %>

app/views/books/edit.html.erb
    	<h1>Editing Book</h1>

        <%= form_for (@book) do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %>

         <br>
        <%= f.submit 'Update Book' %>

         <% end %>


     <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-4">
     <%= render 'books/list', book: @book, user: @user %>
    </div>

    <div class="col-lg-8">
      <h1>Books</h1>

      <table class="table table-striped">
        <thead>
          <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="5"></th>
          </tr>
        </thead>

        <tbody>
         <% @books.each do |book| %>
          <tr>

          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book_path(book), method: :delete, data: {confirm: "本当に消しますか?"}%></td>

          </tr>
         <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-4">
     <%= render 'books/list', book: @book, user: @user %>
    </div>

    <div class="col-lg-8">
      <h1>Book Detail</h1>
      <table class="table table-striped">
        <thead>
          <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="5"></th>
          </tr>
        </thead>

        <tbody>
          <tr>

          <td><%= link_to @book.title, book_path %></td>
          <td><%= @book.body %></td>
          <td><%= link_to 'Edit', edit_book_path %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: {confirm: "本当に消しますか?"}%></td>

          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="wrapper">
    <header>
      <nav class= "navbar navbar-expand-md navbar-dark bg-dark">
      <span class="navbar-brand mb-0 h1" href="#">Bookers</span>
      <div class="justify-content-end">
      <ul class="navbar-nav justify-content-end">
     <% if user_signed_in? %>
      <li class="">
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "Home", books_path %>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= link_to "Users", users_path %>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span><%= link_to "Books", books_path %>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span><%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>

    <% else %>
      <li class="">
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "Home", root_path %>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-link" aria-hidden="true"></span><%= link_to "About", new_booker_path %>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= link_to "sign up", new_user_registration_path %>
      </li>
      <li class="">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span><%= link_to "login", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>
</nav>
</header>
    <%= yield %>
  </div>
  <footer>
     <p>CopyRight Infratop.inc</p>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User Info</h1>

<%= form_for(@user) do |f| %>

    <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">Name</label>
        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail" %>

        <div class="form-group has-icon">
            <div class="user-edit-image">
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
            </div>
            <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        </div>

        <label class="control-label sr-only" for="inputEmail">Introduction</label>
        <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail" %>

        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-lg-4">
     <%= render 'books/list', book: @book, user: @user %>
    </div>

    <div class="col-lg-8">

    	<h1>Users</h1>
      <table class="table table-striped">
        <thead>
          <tr>
          <th>Image</th>
          <th>Name</th>
          <th colspan="3"></th>
          </tr>
        </thead>

    	<tbody>
         <% @users.each do |user| %>
          <tr>


          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(@user) %></td>

          </tr>
         <% end %>
        </tbody>

       </table>

app/views/users/show.html.erb
<p>User#show</p>

<div class="container">
  <div class="row">

    <div class="col-lg-4">

     <h2>User Info</h2>
       <%= @user.name %>
       <%= @user.introduction %>
        <p><%= link_to "編集", books_path %></p>

      <h2>New Book</h2>
       <!-- form_for部分 -->
       <%= form_for(@book) do |f| %>
         <% if @book.errors.any? %>
         <div id="error_explanation">
      <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
       <% end %>

      <h4>Title</h4>
        <%= f.text_field :title %>

      <h4>Opinion</h4>
        <%= f.text_area :body %>

       <br>

       <%= f.submit 'Create Book' %>

       <% end %>
    </div>

    <div class="col-lg-8">
    <h2>Books</h2>

    <table class="table table-striped">
        <thead>
          <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
         <% @books.each do |book| %>
          <tr>

          <td><%= book.title %></td>
          <td><%= book.body %></td>

          </tr>
         <% end %>
        </tbody>
      </table>



    </div>
  </div>
</div>